apiVersion: v1
kind: ResourceQuota
metadata:
  name: tenant-{{ .Values.tenant.name }}-quota
  namespace: tenant-{{ .Values.tenant.name }}
spec:
  hard:
    requests.cpu: {{ .Values.resourceQuota.cpu }}
    requests.memory: {{ .Values.resourceQuota.memory }}
    limits.cpu: {{ .Values.resourceQuota.cpu }}
    limits.memory: {{ .Values.resourceQuota.memory }}
    pods: {{ .Values.resourceQuota.pods }}
    services: {{ .Values.resourceQuota.services }}
    persistentvolumeclaims: {{ .Values.resourceQuota.persistentvolumeclaims }}
