apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.auth.database }}
  POSTGRES_USER: {{ .Values.auth.username }}
  POSTGRES_PASSWORD: {{ .Values.auth.password }}
  POSTGRES_POSTGRES_PASSWORD: {{ .Values.auth.postgresPassword }}
  DATABASE_URL: "postgresql://{{ .Values.auth.username }}:{{ .Values.auth.password }}@{{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local:5432/{{ .Values.auth.database }}?sslmode=disable"
